
---
title: "Estatística Aplicada às Ciências Humanas "
date: ""
output:
  rmdformats::material:
    highlight: kate
    cards: TRUE
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


# **APRESENTAÇÃO**


**Prof. Adriana Andrade (DEMAT/UFRRJ)**
andrade.ufrrj@mail.com

Neste ambiente serão disponibilizados materiais relacionados com a disciplina de Estatística Aplicada às Ciências Humanas. Nessa disciplina são apresentados os conceitos elementares da Estatística, como a representação das variáveis por meio de tabelas, gráficos e medidas resumos.Serão ainda contemplados os conceitos e as técnicas de associação entre duas variáveis, importantes para a avaliação das nossas hipóteses de estudo. Neste curso, a temática da probabilidade será abordada tendo em vista à mensuração da incerteza envolvida nos fenômenos e experimentos de interesse com a exposição dos conceitos elementares e a apresentação das variáveis aleatórias. A disciplina se encerra com a apresentação de técnicas de inferência estatística, tópico que aborda o processo de obtenção de resultados a partir de uma amostra. O software R será utilizado ao longo do curso com o objetivo de proporcionar ao aluno uma aproximação entre teoria e prática.


*************************************************************************************************************************************************************

|AVISO                  |
|-----------------------|
| Informações sobre o funcionamento da disciplina [link]()|

*************************************************************************************************************************************************************

# **PROGRAMA**

- Apresentação da Disciplina

- Apresentação dos dados em Tabelas

- Apresentação dos dados em Gráficos

- Medidas de Posição e Tendência Central

- Medidas de Dispersão

- Assimetria e Boxplot

- Análise Bidimensional - Variáveis Quantitativas

- Análise Bidimensional - Variáveis Qualitativas

- Introdução à Probabilidade

- Introdução à Inferência Estatística

- Intervalo de Confiança

- Teste de Hipóteses

*************************************************************************************************************************************************************


**BIBLIOGRAFIA**

> Bibliografia Básica

LEVIN, Jack; FOX, James Alan. Estatística para ciências humanas. In: Estatística para ciências humanas. Editora Pearso, 2012. 

Wilton O. Bussab; Pedro A. Morettin. Estatística Básica. Editora Saraiva, 2004.



> Bibliografia Complementar

TRIOLA, Mario F. et al. Introdução à estatística. Rio de Janeiro: ltc, 2005.

ANDERSON, D. R.; SWEENEY, D. J.; WILLIAMS, T.A.. Estatística Aplicada à Administração e Economia.. . Cengage Learning.. 2008



*************************************************************************************************************************************************************

# **SOFTWARE**

+ Tutorial de instalação do R [link](https://drive.google.com/file/d/1DzxPxm5EwPAoeKqf-WbhAM0Md3GXYBjw/view?usp=sharing)


**SLIDES DE TUTORIAL DO Jamovi**
- Instalação do Jamovi, grafico e tabelas



*************************************************************************************************************************************************************


# **CRONOGRAMA** 


| Data                  |  Tópico                                          |   Atividade   |
| -------------------   | -----------------------------------------------|---------------|
|	01/06/2021	|	 Apresentação do Curso. Tipos de variáveis. Tabelas	|	Síncrona	|
|	08/06/2021	|	 Tabelas e Gráficos	|	Síncrona	|
|	10/06/2021	|	 Laboratório Software R	|	Síncrona	|
|	15/06/2021	|	 Medidas de Posição	|	Síncrona	|
|	17/06/2021	|		|	Assíncrona	|
|	22/06/2021	|	 Medidas de Posição e Dispersão; Assimetria; Boxplot.	|	Síncrona	|
|	24/06/2021	|		|	Assíncrona	|
|	29/06/2021	|	 Análise bidimensional para variáveis quantitativas	|	Síncrona	|
|	01/07/2021	|	 Laboratório Software R	|	Síncrona	|
|	06/07/2021	|	 Análise bidimensional para variáveis qualitativas	|	Síncrona	|
|	08/07/2021	|	PROVA 1	|		|
|	13/07/2021	|	 Laboratório Software R	|	Síncrona	|
|	15/07/2021	|		|	Assíncrona	|
|	20/07/2021	|	 Introdução à Probabilidade	|	Síncrona	|
|	22/07/2021	|		Apresentação do Trabalho|	Síncrona	|
|	27/07/2021	|	 Distribuição Normal	|	Síncrona	|
|	29/07/2021	|		|	Assíncrona	|
|	03/08/2021	|	 Distribuição Normal	|	Síncrona	|
|	05/08/2021	|		|	Assíncrona	|
|	10/08/2021	|	 Intervalo de Confiança	|	Síncrona	|
|	12/08/2021	|		|	Assíncrona	|
|	17/08/2021	|	 Teste de Hipótese	|	Síncrona	|
|	19/08/2021	|	PROVA 2	|		|
|	24/08/2021	|	Segunda Chamada	|		|
|	26/08/2021	|	OPTATIVA	|		|




# **MATERIAIS**

**IMPORTANTE**
Informações sobre aos cuidados no uso e compartilhamento do material oral e digital disponibilizado no curso. Direitos de imagem de discentes e docentes, bem como a lei de direitos autorais: Estão proibidas quaisquer outras formas de utilização, tais como copiar, editar, adicionar, reduzir, exibir, difundir publicamente, transmitir a terceiros, bem como trocar, emprestar ou praticar qualquer ato de comercialização.
Segundo a deliberação No 289 / 2020 - SAOC (12.28.01.03), que regulamenta as atividades de ensino nesse período em decorrência da pandemia de COVID-19:
*Art. 30. Para fins de Ensino Remoto, o direito de imagem é protegido em relação à transmissão pública, gravação e compartilhamento das atividades…*
*Art. 31 / 1º - Para as atividades remostas síncronas haverá aferição de assiduidade....*

                  
  
|    Tópico                               | Material                | Link              
|-----------------------------------------| -------------------     | ------------------- 
| Tabelas                                 | Videoaula               | [link](https://drive.google.com/file/d/1PDik-3ONTG-Je7b1pBNLtcUo5o4LKZWh/view?usp=sharing)
|                                         | Slides da Aula          | [link](https://drive.google.com/file/d/1ZjiEXm1HgUDhxe_cSsHjjKnNbU6CM66c/view?usp=sharing)
| Gráficos - Variáveis Qualitativas       | Videoaula               | [link](https://youtube.com/playlist?list=PLwrfdhMyXahcRx5v5swTBkh2OgyWOFRgl) 
|                                         | Slides da Aula          | [link](https://drive.google.com/file/d/1W3C4Fwcm7eXhQeQq2Q1Wnt8YbA1ZDEdO/view?usp=sharing)
| Gráficos - Variáveis Quantitativas      | Videoaula               | [link](https://youtube.com/playlist?list=PLwrfdhMyXahcRx5v5swTBkh2OgyWOFRgl) 
|                                         | Slides da Aula          | [link](https://drive.google.com/file/d/14fG4BMQeMz3lhCKrLuK8RjKmgaVXZjjy/view?usp=sharing)
|                                         | **Lista de Exercícios**
| Medidas de Posição e Tendência Central  | Videoaula               | [link](https://youtube.com/playlist?list=PLwrfdhMyXahcRx5v5swTBkh2OgyWOFRgl) 
|                                         | Slides da Aula          | [link](https://drive.google.com/file/d/19CykvMJNImFXDOe43crMEMpPQhSHQ48Q/view?usp=sharing)
| Medidas de Dispersão                    | Videoaula               | [link](https://youtube.com/playlist?list=PLwrfdhMyXahcRx5v5swTBkh2OgyWOFRgl) 
|                                         | Slides da Aula          | [link](https://drive.google.com/file/d/1MPnwV5bfu11CY4S5ZlixICdU28-t23u1/view?usp=sharing)
| Assimetria e Boxplot                    | Videoaula               | [link](https://youtube.com/playlist?list=PLwrfdhMyXahcRx5v5swTBkh2OgyWOFRgl) 
|                                         | Slides da Aula          | [link](https://drive.google.com/file/d/1nXg5wfPJbWhW2Hjw6Fev7oMuwaU45ARd/view?usp=sharing)
|                                         | **Lista de Exercícios** 
| Análise Bidimensional - Quantitativa    | Videoaula               | [link](https://youtube.com/playlist?list=PLwrfdhMyXahcRx5v5swTBkh2OgyWOFRgl)  
|                                         | Slides da Aula          | [link](https://drive.google.com/file/d/1N9Vj9RzuphinVq34F7lIyB6TmtzABM7u/view?usp=sharing)  
|                                         | **Lista de Exercícios** | [link]()      
| Análise Bidimensional - Qualitativa     | Videoaula               | [link](https://youtube.com/playlist?list=PLwrfdhMyXahcRx5v5swTBkh2OgyWOFRgl)  
|                                         | Slides da Aula          | [link](https://drive.google.com/file/d/1NjQgcF4qk1ri7NwzZOXDU4elF7RLb_5W/view?usp=sharing)     
|                                         | **Lista de Exercícios** | [link]() 




*************************************************************************************************************************************************************




